<a href="https://colab.research.google.com/github/Abstrakx/mentoring-fki/blob/main/FKI_Cinsub_Preprocessing_18_Nov_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Preprocessing KM-FKI

**Process :**
1. Import data using `!wget`
2. Read excel data using pandas library
3. Get the `"CODE"` coloumns for processing data
4. Using `data_cleaning` function
5. Get new data into new variable
6. Using pd.concat to get final data and split it into `final_data` and `duplicated_data`
7. If no duplicated data export data frame to excel using to_excel

Ikhwan Data usage:
* Cinsub_18_Nov_2023_FKI_Ikhwan_Alif.xls
* Cinsub_18_Nov_2023_FKI_Ikhwan_Iqbal.xls
* Cinsub_18_Nov_2023_FKI_Ikhwan_Dena.xls

Akhwat Data usage:
* Cinsub_18_Nov_2023_FKI_Akhwat_Afifah.xls
* Cinsub_18_Nov_2023_FKI_Akhwat_Nasyawa.xls

In [17]:
import pandas as pd

# Read dataset
data_afifah = pd.read_excel("Cinsub_18_Nov_2023_FKI_Akhwat_Afifah.xls")
data_nasyawa = pd.read_excel("Cinsub_18_Nov_2023_FKI_Akhwat_Nasyawa.xls")
data_iqbal = pd.read_excel("Cinsub_18_Nov_2023_FKI_Ikhwan_Iqbal.xls")
data_alif = pd.read_excel("Cinsub_18_Nov_2023_FKI_Ikhwan_Alif.xls")
data_dena = pd.read_excel("Cinsub_18_Nov_2023_FKI_Ikhwan_Dena.xls")

df_afifah = pd.DataFrame(data_afifah)
df_nasyawa = pd.DataFrame(data_nasyawa)
df_dena = pd.DataFrame(data_dena)
df_iqbal = pd.DataFrame(data_iqbal)
df_alif = pd.DataFrame(data_alif)

df_afifah

                   TIME                                               CODE
0   2023-11-18 05:05:25  L100230075;\nKaranganyar, 19 April 2005;\nRT 0...
1   2023-11-18 05:06:05  L100230093;\nKaranganyar, 21 October 2003;\nRT...
2   2023-11-18 05:06:43  L100230149;\nPati, 18 December 2004;\nRT 3 RW ...
3   2023-11-18 05:07:02  L100230185;\nDumai, 07 March 2005;\nRT 02 RW 0...
4   2023-11-18 05:07:32                                         L100234022
..                  ...                                                ...
56  2023-11-18 05:29:40  L200230182;\nSragen, 08 May 2005;\nRT 27 RW 12...
57  2023-11-18 05:32:01  L100230160;\nKaranganyar, 01 July 2005;\nRT 01...
58  2023-11-18 05:34:39  L100230008;\nWonosobo, 16 November 2003;\nRT 0...
59  2023-11-18 05:34:53  L200239192;\nSragen, 02 January 2005;\nRT 07 R...
60  2023-11-18 05:37:09  L100230199;\nSragen, 30 December 2004;\nRT 1 R...

[61 rows x 2 columns]

In [18]:
df_code_afifah = df_afifah[0:]["CODE"]
df_code_nasyawa = df_nasyawa[0:]["CODE"]
df_code_iqbal = df_iqbal[0:]["CODE"]
df_code_dena = df_dena[0:]["CODE"]
df_code_alif = df_alif[0:]["CODE"]

df_code_afifah

0     L100230075;\nKaranganyar, 19 April 2005;\nRT 0...
1     L100230093;\nKaranganyar, 21 October 2003;\nRT...
2     L100230149;\nPati, 18 December 2004;\nRT 3 RW ...
3     L100230185;\nDumai, 07 March 2005;\nRT 02 RW 0...
4                                            L100234022
                            ...
56    L200230182;\nSragen, 08 May 2005;\nRT 27 RW 12...
57    L100230160;\nKaranganyar, 01 July 2005;\nRT 01...
58    L100230008;\nWonosobo, 16 November 2003;\nRT 0...
59    L200239192;\nSragen, 02 January 2005;\nRT 07 R...
60    L100230199;\nSragen, 30 December 2004;\nRT 1 R...
Name: CODE, Length: 61, dtype: object

In [19]:
def data_cleaning(data_frame):
  cleaning_data = []

  for i in data_frame.to_list():
    element = i.split(';\n')
    if len(element) == 3:
      cleaning_data.append(element)
  return cleaning_data

In [20]:
data_cleaned_afifah = data_cleaning(df_code_afifah)
data_cleaned_nasyawa = data_cleaning(df_code_nasyawa)
data_cleaned_dena = data_cleaning(df_code_dena)
data_cleaned_iqbal = data_cleaning(df_code_iqbal)
data_cleaned_alif = data_cleaning(df_code_alif)

data_cleaned_afifah

[['L100230075',
  'Karanganyar, 19 April 2005',
  'RT 04 RW 02, Kelurahan Jatipuro, Kecamatan Jatipuro,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L100230093',
  'Karanganyar, 21 October 2003',
  'RT 4 RW 4, Kelurahan Kragan, Kecamatan Gondangrejo,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L100230149',
  'Pati, 18 December 2004',
  'RT 3 RW 2, Kelurahan Mojoagung, Kecamatan Trangkil,  Kabupaten Pati, Jawa Tengah'],
 ['L100230185',
  'Dumai, 07 March 2005',
  'RT 02 RW 08, Kelurahan Sidanegara, Kecamatan Cilacap Tengah,  Kabupaten Cilacap, Jawa Tengah'],
 ['L100230144',
  'Sukoharjo, 27 February 2005',
  'RT 4 RW 1, Kelurahan Madegondo, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L100230153',
  'Boyolali, 27 June 2005',
  'RT 2 RW 5, Kelurahan Donohudan, Kecamatan Ngemplak,  Kabupaten Boyolali, Jawa Tengah'],
 ['L200230243',
  'Magetan, 06 February 2005',
  'RT 005 RW 002, Kelurahan Setren, Kecamatan Bendo,  Kabupaten Magetan, Jawa Timur'],
 ['L200230259',
  'Karanganyar, 16 June 2005',
  'RT 4 RW 11, Kelurahan Jaten, Kecamatan Jaten,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L100230067',
  'Surakarta, 17 March 2005',
  'RT 07 RW 03, Kelurahan Ngaru Aru, Kecamatan Banyudono,  Kabupaten Boyolali, Jawa Tengah'],
 ['L100230146',
  'Surakarta, 31 March 2005',
  'RT 1 RW 4, Kelurahan Banaran, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L100230082',
  'Tegal, 02 January 2004',
  'RT 8 RW 2, Kelurahan Bandasari, Kecamatan Dukuhturi,  Kabupaten Tegal, Jawa Tengah'],
 ['L200230156',
  'Bangka Tengah, 21 February 2005',
  'RT 009 RW 000, Kelurahan Koba, Kecamatan Koba,  Kabupaten Bangka Tengah, Kepulauan Bangka Belitung'],
 ['L100230010',
  'Kab. Semarang, 28 February 2004',
  'RT 02 RW 03, Kelurahan Karangjati, Kecamatan Bergas,  Kabupaten Semarang, Jawa Tengah'],
 ['L200230050',
  'Klaten, 27 September 2003',
  'RT 1 RW 26, Kelurahan Jimbung, Kecamatan Kalikotes,  Kabupaten Klaten, Jawa Tengah'],
 ['L200230064',
  'Klaten, 22 March 2004',
  'RT 008 RW 004, Kelurahan Sidowayah, Kecamatan Polanharjo,  Kabupaten Klaten, Jawa Tengah'],
 ['L100230237',
  'Sragen, 08 February 2005',
  'RT 2 RW 15, Kelurahan Tangkil, Kecamatan Sragen,  Kabupaten Sragen, Jawa Tengah'],
 ['L100230220',
  'Pati, 07 August 2005',
  'RT 4 RW 3, Kelurahan Bumirejo, Kecamatan Margorejo,  Kabupaten Pati, Jawa Tengah'],
 ['L100230030',
  'Rembang, 08 September 2005',
  'RT 03 RW 07, Kelurahan Sumberjo, Kecamatan Rembang,  Kabupaten Rembang, Jawa Tengah'],
 ['L200230074',
  'Pemalang, 22 November 2005',
  'RT 4 RW 5, Kelurahan Kebondalem, Kecamatan Pemalang,  Kabupaten Pemalang, Jawa Tengah'],
 ['L100230187',
  'Klaten, 13 June 2005',
  'RT 002 RW 001, Kelurahan Bulurejo, Kecamatan Juwiring,  Kabupaten Klaten, Jawa Tengah'],
 ['L100230142',
  'Klaten, 01 July 2005',
  'RT 06 RW 03, Kelurahan Gombang, Kecamatan Cawas,  Kabupaten Klaten, Jawa Tengah'],
 ['L100230189',
  'Pemalang, 11 November 2004',
  'RT 01 RW 07, Kelurahan Kaligelang, Kecamatan Taman,  Kabupaten Pemalang, Jawa Tengah'],
 ['L100230009',
  'Boyolali, 19 November 2003',
  'RT 04 RW 02, Kelurahan Cibeber, Kecamatan Cibeber,  Kota Cilegon, Banten'],
 ['L100230257',
  'Boyolali, 08 August 2004',
  'RT 1 RW 3, Kelurahan Kembangkuning, Kecamatan Cepogo,  Kabupaten Boyolali, Jawa Tengah'],
 ['L100230198',
  'Purwodadi, 28 October 2005',
  'RT 013 RW 03, Kelurahan Purwodadi, Kecamatan Tebing Tinggi,  Kabupaten Tanjung Jabung Barat, Jambi'],
 ['L100230139',
  'Surakarta, 17 September 2005',
  'RT 03 RW 10, Kelurahan Gonilan, Kecamatan Kartasura,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L200230165',
  'Magetan, 20 June 2004',
  'RT 01 RW 01, Kelurahan Karangsono, Kecamatan Barat,  Kabupaten Magetan, Jawa Timur'],
 ['L100230170',
  'Boyolali, 23 February 2004',
  'RT 4 RW 5, Kelurahan Urutsewu, Kecamatan Ampel,  Kabupaten Boyolali, Jawa Tengah'],
 ['L100230203',
  'Klaten, 19 May 2005',
  'RT 13 RW 4, Kelurahan Cokro, Kecamatan Tulung,  Kabupaten Klaten, Jawa Tengah'],
 ['L100230169',
  'Sragen, 28 February 2006',
  'RT 22 RW 6, Kelurahan Bentak, Kecamatan Sidoharjo,  Kabupaten Sragen, Jawa Tengah'],
 ['L200230151',
  'Pati, 04 September 2004',
  'RT 02 RW 04, Kelurahan Trimulyo, Kecamatan Juwana,  Kabupaten Pati, Jawa Tengah'],
 ['L200230065',
  'Sukoharjo, 01 June 2005',
  'RT 1 RW 12, Kelurahan Gayam, Kecamatan Sukoharjo,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L100230141',
  'Jakarta, 06 December 2004',
  'RT 02 RW 07, Kelurahan Pondok, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L200234269',
  'Bandung, 03 February 2005',
  'RT 004 RW 005, Kelurahan Muktiharjo, Kecamatan Margorejo,  Kabupaten Pati, Jawa Tengah'],
 ['L200234060',
  'Surakarta, 11 November 2004',
  'RT 2 RW 3, Kelurahan Laweyan, Kecamatan Laweyan,  Kota Surakarta, Jawa Tengah'],
 ['L100230129',
  'Wonogiri, 23 November 2005',
  'RT 01 RW 04, Kelurahan Pule, Kecamatan Selogiri,  Kabupaten Wonogiri, Jawa Tengah'],
 ['L200230101',
  'Karanganyar, 06 September 2004',
  'RT 4 RW 11, Kelurahan Bolon, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L200230093',
  'Gunung Makmur, 03 December 2004',
  'RT 014 RW 003, Kelurahan Gunung Makmur, Kecamatan Antang Kalang,  Kabupaten Kotawaringin Timur, Kalimantan Tengah'],
 ['L100230094',
  'Banten, 29 September 2005',
  'RT 09 RW 09, Kelurahan Jatireja, Kecamatan Cikarang Timur,  Kabupaten Bekasi, Jawa Barat'],
 ['L100230227',
  'Karanganyar, 20 December 2004',
  'RT 009 RW 005, Kelurahan Kamalaputi, Kecamatan Kota Waingapu,  Kabupaten Sumba Timur, Nusa Tenggara Timur'],
 ['L100230216',
  'Wonogiri, 23 February 2005',
  'RT 2 RW 5, Kelurahan Jendi, Kecamatan Selogiri,  Kabupaten Wonogiri, Jawa Tengah'],
 ['L100230259',
  'Pekalongan, 14 December 2004',
  'RT 1 RW 3, Kelurahan Wiradesa, Kecamatan Wiradesa,  Kabupaten Pekalongan, Jawa Tengah'],
 ['L100230270',
  'Bogor, 30 November 2003',
  'RT 04 RW 08, Kelurahan Cogreg, Kecamatan Parung,  Kabupaten Bogor, Jawa Barat'],
 ['L100230264',
  'Kota Madiun, 04 January 2005',
  'RT 50 RW 15, Kelurahan Kejuron, Kecamatan Taman,  Kota Madiun, Jawa Timur'],
 ['L100230209',
  'Surakarta, 24 November 2003',
  'RT 03 RW 03, Kelurahan Gajahan, Kecamatan Pasar Kliwon,  Kota Surakarta, Jawa Tengah'],
 ['L100230258',
  'Jakarta, 15 June 2005',
  'RT 5 RW 3, Kelurahan Cipulir, Kecamatan Kebayoran Lama,  Kota Jakarta Selatan, Dki Jakarta'],
 ['L200230043',
  'Surakarta, 05 November 2005',
  'RT 1 RW 13, Kelurahan Pajang, Kecamatan Laweyan,  Kota Surakarta, Jawa Tengah'],
 ['L100234253',
  'Grobogan, 29 June 2005',
  'RT 1 RW 7, Kelurahan Jambon, Kecamatan Pulokulon,  Kabupaten Grobogan, Jawa Tengah'],
 ['L200230075',
  'Sukoharjo, 27 October 2004',
  'RT 01 RW 04, Kelurahan Kertonatan, Kecamatan Kartasura,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L200230042',
  'Sukoharjo, 19 April 2005',
  'RT 1 RW 2, Kelurahan Parangjoro, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L100234247',
  'Surakarta, 24 December 2005',
  'RT 003 RW 011, Kelurahan Kerten, Kecamatan Laweyan,  Kota Surakarta, Jawa Tengah'],
 ['L200230033',
  'Surakarta, 30 September 2004',
  'RT 3 RW 5, Kelurahan Bumi, Kecamatan Laweyan,  Kota Surakarta, Jawa Tengah'],
 ['L100230049',
  'Boyolali, 17 August 2004',
  'RT 06 RW 03, Kelurahan Pulisen, Kecamatan Boyolali,  Kabupaten Boyolali, Jawa Tengah'],
 ['L100230035',
  'Ngawi, 14 November 2005',
  'RT 11 RW 2, Kelurahan Kedungharjo, Kecamatan Mantingan,  Kabupaten Ngawi, Jawa Timur'],
 ['L100230032',
  'Surakarta, 25 February 2005',
  'RT 4 RW 1, Kelurahan Karangasem, Kecamatan Laweyan,  Kota Surakarta, Jawa Tengah'],
 ['L200230182',
  'Sragen, 08 May 2005',
  'RT 27 RW 12, Kelurahan Ngarum, Kecamatan Ngrampal,  Kabupaten Sragen, Jawa Tengah'],
 ['L100230160',
  'Karanganyar, 01 July 2005',
  'RT 01 RW 06, Kelurahan Bakalan, Kecamatan Jumapolo,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L100230008',
  'Wonosobo, 16 November 2003',
  'RT 03 RW 06, Kelurahan Bumireso, Kecamatan Wonosobo,  Kabupaten Wonosobo, Jawa Tengah'],
 ['L200239192',
  'Sragen, 02 January 2005',
  'RT 07 RW 0, Kelurahan Donoyudan, Kecamatan Kalijambe,  Kabupaten Sragen, Jawa Tengah'],
 ['L100230199',
  'Sragen, 30 December 2004',
  'RT 1 RW 1, Kelurahan Jati, Kecamatan Masaran,  Kabupaten Sragen, Jawa Tengah']]

In [21]:
new_data_afifah = pd.DataFrame(data_cleaned_afifah, columns=("NIM", "TTL", "Alamat"))
new_data_nasyawa = pd.DataFrame(data_cleaned_nasyawa, columns=("NIM", "TTL", "Alamat"))
new_data_dena = pd.DataFrame(data_cleaned_dena, columns=("NIM", "TTL", "Alamat"))
new_data_iqbal = pd.DataFrame(data_cleaned_iqbal, columns=("NIM", "TTL", "Alamat"))
new_data_alif = pd.DataFrame(data_cleaned_alif, columns=("NIM", "TTL", "Alamat"))

new_data_iqbal

,NIM,TTL,Alamat
0,L100230145,"Klaten, 17 March 2005","RT 007 RW 003, Kelurahan Pandanan, Kecamatan W..."
1,L200230040,"Sragen, 16 June 2005","RT 8 RW 4, Kelurahan Banaran, Kecamatan Kalija..."
2,L200230066,"Sragen, 06 December 2004","RT 9 RW 0, Kelurahan Mojodoyong, Kecamatan Ked..."
3,L200230219,"Karanganyar, 27 March 2005","RT 02 RW 14, Kelurahan Papahan, Kecamatan Tasi..."
4,L200230218,"Surakarta, 13 November 2004","RT 3 RW 11, Kelurahan Nusukan, Kecamatan Banja..."
...,...,...,...
77,L200230202,"Subang, 01 October 2005","RT 06 RW 02, Kelurahan Pabuaran, Kecamatan Pab..."
78,L100230151,"Surakarta, 25 June 2004","RT 03 RW 12, Kelurahan Mangkubumen, Kecamatan ..."
79,L200230079,"Karanganyar, 03 July 2005","RT 5 RW 11, Kelurahan Ngadirejo, Kecamatan Moj..."
80,L100230045,"Sragen, 27 November 2004","RT 5 RW 2, Kelurahan Bentak, Kecamatan Sidohar..."
81,L100230029,"Ngawi, 09 June 2002","RT 5 RW 2, Kelurahan Pager, Kecamatan Kaliwung..."

In [22]:
filtered_df_afifah = new_data_afifah[new_data_afifah['NIM'].str.startswith('L')]
filtered_df_nasyawa = new_data_nasyawa[new_data_nasyawa['NIM'].str.startswith('L')]
filtered_df_dena = new_data_dena[new_data_dena['NIM'].str.startswith('L')]
filtered_df_iqbal = new_data_iqbal[new_data_iqbal['NIM'].str.startswith('L')]
filtered_df_alif = new_data_alif[new_data_alif['NIM'].str.startswith('L')]

filtered_df_afifah

,NIM,TTL,Alamat
0,L100230075,"Karanganyar, 19 April 2005","RT 04 RW 02, Kelurahan Jatipuro, Kecamatan Jat..."
1,L100230093,"Karanganyar, 21 October 2003","RT 4 RW 4, Kelurahan Kragan, Kecamatan Gondang..."
2,L100230149,"Pati, 18 December 2004","RT 3 RW 2, Kelurahan Mojoagung, Kecamatan Tran..."
3,L100230185,"Dumai, 07 March 2005","RT 02 RW 08, Kelurahan Sidanegara, Kecamatan C..."
4,L100230144,"Sukoharjo, 27 February 2005","RT 4 RW 1, Kelurahan Madegondo, Kecamatan Grog..."
5,L100230153,"Boyolali, 27 June 2005","RT 2 RW 5, Kelurahan Donohudan, Kecamatan Ngem..."
6,L200230243,"Magetan, 06 February 2005","RT 005 RW 002, Kelurahan Setren, Kecamatan Ben..."
7,L200230259,"Karanganyar, 16 June 2005","RT 4 RW 11, Kelurahan Jaten, Kecamatan Jaten, ..."
8,L100230067,"Surakarta, 17 March 2005","RT 07 RW 03, Kelurahan Ngaru Aru, Kecamatan Ba..."
9,L100230146,"Surakarta, 31 March 2005","RT 1 RW 4, Kelurahan Banaran, Kecamatan Grogol..."
10,L100230082,"Tegal, 02 January 2004","RT 8 RW 2, Kelurahan Bandasari, Kecamatan Duku..."
11,L200230156,"Bangka Tengah, 21 February 2005","RT 009 RW 000, Kelurahan Koba, Kecamatan Koba,..."
12,L100230010,"Kab. Semarang, 28 February 2004","RT 02 RW 03, Kelurahan Karangjati, Kecamatan B..."
13,L200230050,"Klaten, 27 September 2003","RT 1 RW 26, Kelurahan Jimbung, Kecamatan Kalik..."
14,L200230064,"Klaten, 22 March 2004","RT 008 RW 004, Kelurahan Sidowayah, Kecamatan ..."
15,L100230237,"Sragen, 08 February 2005","RT 2 RW 15, Kelurahan Tangkil, Kecamatan Srage..."
16,L100230220,"Pati, 07 August 2005","RT 4 RW 3, Kelurahan Bumirejo, Kecamatan Margo..."
17,L100230030,"Rembang, 08 September 2005","RT 03 RW 07, Kelurahan Sumberjo, Kecamatan Rem..."
18,L200230074,"Pemalang, 22 November 2005","RT 4 RW 5, Kelurahan Kebondalem, Kecamatan Pem..."
19,L100230187,"Klaten, 13 June 2005","RT 002 RW 001, Kelurahan Bulurejo, Kecamatan J..."
20,L100230142,"Klaten, 01 July 2005","RT 06 RW 03, Kelurahan Gombang, Kecamatan Cawa..."
21,L100230189,"Pemalang, 11 November 2004","RT 01 RW 07, Kelurahan Kaligelang, Kecamatan T..."
22,L100230009,"Boyolali, 19 November 2003","RT 04 RW 02, Kelurahan Cibeber, Kecamatan Cibe..."
23,L100230257,"Boyolali, 08 August 2004","RT 1 RW 3, Kelurahan Kembangkuning, Kecamatan ..."
24,L100230198,"Purwodadi, 28 October 2005","RT 013 RW 03, Kelurahan Purwodadi, Kecamatan T..."
25,L100230139,"Surakarta, 17 September 2005","RT 03 RW 10, Kelurahan Gonilan, Kecamatan Kart..."
26,L200230165,"Magetan, 20 June 2004","RT 01 RW 01, Kelurahan Karangsono, Kecamatan B..."
27,L100230170,"Boyolali, 23 February 2004","RT 4 RW 5, Kelurahan Urutsewu, Kecamatan Ampel..."
28,L100230203,"Klaten, 19 May 2005","RT 13 RW 4, Kelurahan Cokro, Kecamatan Tulung,..."
29,L100230169,"Sragen, 28 February 2006","RT 22 RW 6, Kelurahan Bentak, Kecamatan Sidoha..."
30,L200230151,"Pati, 04 September 2004","RT 02 RW 04, Kelurahan Trimulyo, Kecamatan Juw..."
31,L200230065,"Sukoharjo, 01 June 2005","RT 1 RW 12, Kelurahan Gayam, Kecamatan Sukohar..."
32,L100230141,"Jakarta, 06 December 2004","RT 02 RW 07, Kelurahan Pondok, Kecamatan Grogo..."
33,L200234269,"Bandung, 03 February 2005","RT 004 RW 005, Kelurahan Muktiharjo, Kecamatan..."
34,L200234060,"Surakarta, 11 November 2004","RT 2 RW 3, Kelurahan Laweyan, Kecamatan Laweya..."
35,L100230129,"Wonogiri, 23 November 2005","RT 01 RW 04, Kelurahan Pule, Kecamatan Selogir..."
36,L200230101,"Karanganyar, 06 September 2004","RT 4 RW 11, Kelurahan Bolon, Kecamatan Colomad..."
37,L200230093,"Gunung Makmur, 03 December 2004","RT 014 RW 003, Kelurahan Gunung Makmur, Kecama..."
38,L100230094,"Banten, 29 September 2005","RT 09 RW 09, Kelurahan Jatireja, Kecamatan Cik..."
39,L100230227,"Karanganyar, 20 December 2004","RT 009 RW 005, Kelurahan Kamalaputi, Kecamatan..."
40,L100230216,"Wonogiri, 23 February 2005","RT 2 RW 5, Kelurahan Jendi, Kecamatan Selogiri..."
41,L100230259,"Pekalongan, 14 December 2004","RT 1 RW 3, Kelurahan Wiradesa, Kecamatan Wirad..."
42,L100230270,"Bogor, 30 November 2003","RT 04 RW 08, Kelurahan Cogreg, Kecamatan Parun..."
43,L100230264,"Kota Madiun, 04 January 2005","RT 50 RW 15, Kelurahan Kejuron, Kecamatan Tama..."
44,L100230209,"Surakarta, 24 November 2003","RT 03 RW 03, Kelurahan Gajahan, Kecamatan Pasa..."
45,L100230258,"Jakarta, 15 June 2005","RT 5 RW 3, Kelurahan Cipulir, Kecamatan Kebayo..."
46,L200230043,"Surakarta, 05 November 2005","RT 1 RW 13, Kelurahan Pajang, Kecamatan Laweya..."
47,L100234253,"Grobogan, 29 June 2005","RT 1 RW 7, Kelurahan Jambon, Kecamatan Pulokul..."
48,L200230075,"Sukoharjo, 27 October 2004","RT 01 RW 04, Kelurahan Kertonatan, Kecamatan K..."
49,L200230042,"Sukoharjo, 19 April 2005","RT 1 RW 2, Kelurahan Parangjoro, Kecamatan Gro..."
50,L100234247,"Surakarta, 24 December 2005","RT 003 RW 011, Kelurahan Kerten, Kecamatan Law..."
51,L200230033,"Surakarta, 30 September 2004","RT 3 RW 5, Kelurahan Bumi, Kecamatan Laweyan, ..."
52,L100230049,"Boyolali, 17 August 2004","RT 06 RW 03, Kelurahan Pulisen, Kecamatan Boyo..."
53,L100230035,"Ngawi, 14 November 2005","RT 11 RW 2, Kelurahan Kedungharjo, Kecamatan M..."
54,L100230032,"Surakarta, 25 February 2005","RT 4 RW 1, Kelurahan Karangasem, Kecamatan Law..."
55,L200230182,"Sragen, 08 May 2005","RT 27 RW 12, Kelurahan Ngarum, Kecamatan Ngram..."
56,L100230160,"Karanganyar, 01 July 2005","RT 01 RW 06, Kelurahan Bakalan, Kecamatan Juma..."
57,L100230008,"Wonosobo, 16 November 2003","RT 03 RW 06, Kelurahan Bumireso, Kecamatan Won..."
58,L200239192,"Sragen, 02 January 2005","RT 07 RW 0, Kelurahan Donoyudan, Kecamatan Kal..."
59,L100230199,"Sragen, 30 December 2004","RT 1 RW 1, Kelurahan Jati, Kecamatan Masaran, ..."

In [23]:
combinated_data_ikhwan = pd.concat([filtered_df_alif, filtered_df_iqbal, filtered_df_dena], ignore_index=True)
combinated_data_akhwat = pd.concat([filtered_df_nasyawa, filtered_df_afifah], ignore_index=True)

final_data_akhwat = combinated_data_akhwat
duplicated_data_akhwat = combinated_data_akhwat[combinated_data_akhwat.duplicated()]
final_data_ikhwan = combinated_data_ikhwan
duplicated_data_ikhwan = combinated_data_ikhwan[combinated_data_ikhwan.duplicated()]

final_data_akhwat

,NIM,TTL,Alamat
0,L100230226,"Boyolali, 22 September 2004","RT 4 RW 4, Kelurahan Mojosongo, Kecamatan Mojo..."
1,L100230085,"Brebes, 17 September 2003","RT 02 RW 06, Kelurahan Pasar Batang, Kecamatan..."
2,L200230248,"Surakarta, 03 February 2005","RT 5 RW 28, Kelurahan Mojosongo, Kecamatan Jeb..."
3,L100234263,"Karanganyar, 22 November 2004","RT 9 RW 6, Kelurahan Ngijo, Kecamatan Tasikmad..."
4,L100234250,"Ponorogo, 25 July 2004","RT 01 RW 01, Kelurahan Patihan Kidul, Kecamata..."
...,...,...,...
111,L200230182,"Sragen, 08 May 2005","RT 27 RW 12, Kelurahan Ngarum, Kecamatan Ngram..."
112,L100230160,"Karanganyar, 01 July 2005","RT 01 RW 06, Kelurahan Bakalan, Kecamatan Juma..."
113,L100230008,"Wonosobo, 16 November 2003","RT 03 RW 06, Kelurahan Bumireso, Kecamatan Won..."
114,L200239192,"Sragen, 02 January 2005","RT 07 RW 0, Kelurahan Donoyudan, Kecamatan Kal..."
115,L100230199,"Sragen, 30 December 2004","RT 1 RW 1, Kelurahan Jati, Kecamatan Masaran, ..."

In [24]:
duplicated_data_akhwat

Empty DataFrame
Columns: [NIM, TTL, Alamat]
Index: []

In [25]:
final_data_ikhwan

,NIM,TTL,Alamat
0,L200230073,"Karanganyar, 25 April 2005","RT 04 RW 07, Kelurahan Kebak, Kecamatan Kebakk..."
1,L200234233,"Klaten, 02 October 2004","RT 02 RW 09, Kelurahan Cawas, Kecamatan Cawas,..."
2,L100230111,"Sragen, 17 September 2005","RT 007 RW 000, Kelurahan Pilangsari, Kecamatan..."
3,L100230087,"Sila, 14 September 2004","RT 04 RW 02, Kelurahan Santi, Kecamatan Mpunda..."
4,L100230092,"Sragen, 07 November 2004","RT 25 RW 08, Kelurahan Puro, Kecamatan Karangm..."
...,...,...,...
143,L100230042,"Sukoharjo, 05 February 2005","RT 02 RW 06, Kelurahan Karangasem, Kecamatan L..."
144,L100230025,"Karang Asem, 01 October 2004","RT 2 RW 4, Kelurahan Musuk, Kecamatan Musuk, ..."
145,L100230044,"Wonogiri, 21 June 2004","RT 2 RW 14, Kelurahan Baturetno, Kecamatan Bat..."
146,L200230208,"Ngawi, 14 May 2005","RT 2 RW 1, Kelurahan Beran, Kecamatan Ngawi, ..."
147,L100230121,"Klaten, 27 July 2004","RT 16 RW 07, Kelurahan Jelobo, Kecamatan Wonos..."

In [26]:
duplicated_data_ikhwan

Empty DataFrame
Columns: [NIM, TTL, Alamat]
Index: []

In [27]:
final_data_akhwat.to_excel("Cinsub_18_Nov_2023_FKI_Akhwat_Final.xlsx")
final_data_ikhwan.to_excel("Cinsub_18_Nov_2023_FKI_Ikhwan_Final.xlsx")