<a href="https://colab.research.google.com/github/Abstrakx/mentoring-fki/blob/main/FKI_Cinsub_Preprocessing_9_Dec_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Preprocessing KM-FKI

**Process :**
1. Import data using `!wget`
2. Read excel data using pandas library
3. Get the `"CODE"` coloumns for processing data
4. Using `data_cleaning` function
5. Get new data into new variable
6. Using pd.concat to get final data and split it into `final_data` and `duplicated_data`
7. If no duplicated data export data frame to excel using to_excel

Ikhwan Data usage:
* Cinsub_9_Des_2023_FKI_Ikhwan_iqbal.xls
* Cinsub_9_Des_2023_FKI_Ikhwan_iqbal_1.xls

Akhwat Data usage:
* Cinsub_9_Des_2023_FKI_Akhwat_Afifah.xls
* Cinsub_9_Des_2023_FKI_Akhwat_Afifah_1.xls
* Cinsub_9_Des_2023_FKI_Akhwat_Ami.xls

In [ ]:
import pandas as pd

# Read dataset
data_afifah = pd.read_excel("Cinsub_9_Des_2023_FKI_Akhwat_Afifah.xls")
data_afifah_1 = pd.read_excel("Cinsub_9_Des_2023_FKI_Akhwat_Afifah_1.xls")
data_ami = pd.read_excel("Cinsub_9_Des_2023_FKI_Akhwat_Ami.xls")
data_iqbal = pd.read_excel("Cinsub_9_Des_2023_FKI_Ikhwan_Iqbal.xls")
data_iqbal_1 = pd.read_excel("Cinsub_9_Des_2023_FKI_Ikhwan_Iqbal_1.xls")

df_afifah = pd.DataFrame(data_afifah)
df_afifah_1 = pd.DataFrame(data_afifah_1)
df_ami = pd.DataFrame(data_ami)
df_iqbal = pd.DataFrame(data_iqbal)
df_iqbal_1 = pd.DataFrame(data_iqbal_1)

df_afifah

                   TIME                                               CODE
0   2023-12-09 05:31:59  L100230058;\nKaranganyar, 10 April 2001;\nRT 0...
1   2023-12-09 05:32:26  L100230100;\nWonogiri, 14 September 2005;\nRT ...
2   2023-12-09 05:32:42  L100230095;\nSukoharjo, 08 February 2005;\nRT ...
3   2023-12-09 05:33:22                                         L200234059
4   2023-12-09 05:33:34  L200234018;\nSalatiga, 05 May 2005;\nRT 01 RW ...
5   2023-12-09 05:34:09  L200234096;\nKaranganyar, 03 June 2005;\nRT 06...
6   2023-12-09 05:34:46  L100230079;\nGrobogan, 16 April 2005;\nRT 5 RW...
7   2023-12-09 05:35:16  L200230022;\nSragen, 10 November 2004;\nRT 04 ...
8   2023-12-09 05:35:31  L200230026;\nSurabaya, 03 May 2005;\nRT 5 RW 4...
9   2023-12-09 05:35:44  L100234250;\nPonorogo, 25 July 2004;\nRT 01 RW...
10  2023-12-09 05:35:55  L100234263;\nKaranganyar, 22 November 2004;\nR...
11  2023-12-09 05:36:09  L100234195;\nPemalang, 01 November 2004;\nRT 3...
12  2023-12-09 05:36:31  L100230227;\nKaranganyar, 20 December 2004;\nR...
13  2023-12-09 05:36:49                                         L100220059
14  2023-12-09 05:37:04  L100230144;\nSukoharjo, 27 February 2005;\nRT ...
15  2023-12-09 05:37:26  L100230184;\nNgawi, 19 October 2004;\nRT 2 RW ...
16  2023-12-09 05:37:40  L100230196;\nKlaten, 14 January 2005;\nRT 3 RW...
17  2023-12-09 05:38:02  L100230149;\nPati, 18 December 2004;\nRT 3 RW ...
18  2023-12-09 05:38:10  L200230101;\nKaranganyar, 06 September 2004;\n...
19  2023-12-09 05:38:18  L200230093;\nGunung Makmur, 03 December 2004;\...
20  2023-12-09 05:38:31  L200230038;\nKaranganyar, 26 March 2005;\nRT 1...
21  2023-12-09 05:38:42  L200230056;\nLubuk Betung, 18 March 2005;\nRT ...
22  2023-12-09 05:38:50  L200230061;\nKlaten, 19 October 2004;\nRT 03 R...
23  2023-12-09 05:39:02  L100234243;\nKlaten, 24 February 2006;\nRT 14 ...
24  2023-12-09 05:39:26  L100230054;\nKaranganyar, 29 September 2005;\n...
25  2023-12-09 05:39:37  L200230065;\nSukoharjo, 01 June 2005;\nRT 1 RW...
26  2023-12-09 05:39:46  L200230033;\nSurakarta, 30 September 2004;\nRT...
27  2023-12-09 05:39:54  L100230099;\nMagetan, 21 March 2005;\nRT 1 RW ...
28  2023-12-09 05:40:15  L100230094;\nBanten, 29 September 2005;\nRT 09...
29  2023-12-09 05:40:26  L100230138;\nSuka Cinta, 17 June 2005;\nRT 01 ...
30  2023-12-09 05:40:36  L200230257;\nWonogiri, 17 May 2004;\nRT 01 RW ...
31  2023-12-09 05:40:45  L200239281;\nSurakarta, 07 December 2005;\nRT ...
32  2023-12-09 05:40:56  L200230245;\nBogor, 08 August 2005;\nRT 001 RW...
33  2023-12-09 05:41:05  L100230238;\nNganjuk, 24 September 2004;\nRT 1...
34  2023-12-09 05:41:32  L100230229;\nSukoharjo, 16 June 2005;\nRT 02 R...
35  2023-12-09 05:41:43  L200230259;\nKaranganyar, 16 June 2005;\nRT 4 ...
36  2023-12-09 05:42:02  L200230206;\nSurakarta, 09 April 2005;\nRT 005...
37  2023-12-09 05:43:43  L100230176;\nSukoharjo, 13 May 2005;\nRT 1 RW ...
38  2023-12-09 05:43:54  L100230164;\nBoyolali, 11 April 2005;\nRT 3 RW...
39  2023-12-09 05:46:41  L200230156;\nBangka Tengah, 21 February 2005;\...
40  2023-12-09 05:47:01  L200230137;\nGrobogan, 12 November 2005;\nRT 0...
41  2023-12-09 05:47:46                                         L200230214
42  2023-12-09 05:48:07  L200239192;\nSragen, 02 January 2005;\nRT 07 R...
43  2023-12-09 05:48:23  L200239282;\nKlaten, 04 September 2004;\nRT 7 ...

In [ ]:
df_code_afifah = df_afifah[0:]["CODE"]
df_code_afifah_1 = df_afifah_1[0:]["CODE"]
df_code_ami = df_ami[0:]["CODE"]
df_code_iqbal = df_iqbal[0:]["CODE"]
df_code_iqbal_1 = df_iqbal_1[0:]["CODE"]

df_code_ami

0     L100230154;\nSurakarta, 23 December 2004;\nRT ...
1     L100230219;\nYogyakarta, 21 January 2004;\nRT ...
2     L100230141;\nJakarta, 06 December 2004;\nRT 02...
3     L100230179;\nWonogiri, 18 June 2004;\nRT 2 RW ...
4     L100230005;\nSukoharjo, 07 February 2005;\nRT ...
5     L100230085;\nBrebes, 17 September 2003;\nRT 02...
6     L100230088;\nWonogiri, 27 August 2005;\nRT 03 ...
7     L100230007;\nSidoarjo, Jawa Timur, 20 May 2005...
8     L100230139;\nSurakarta, 17 September 2005;\nRT...
9     L100230198;\nPurwodadi, 28 October 2005;\nRT 0...
10    L100230246;\nJakarta, 02 April 2005;\nRT 6 RW ...
11    L100234234;\nSurakarta, 19 May 2005;\nRT 02 RW...
12    L100230021;\nGrobogan, 12 February 2005;\nRT 3...
13    L200230277;\nBoyolali, 01 February 2006;\nRT 0...
14    L100230264;\nKota Madiun, 04 January 2005;\nRT...
15    L100230216;\nWonogiri, 23 February 2005;\nRT 2...
16    L200230228;\nEnde, 18 January 2005;\nRT 0 RW 0...
17    L200230043;\nSurakarta, 05 November 2005;\nRT ...
18    L100230110;\nMagetan, 14 September 2004;\nRT 1...
19    L100230104;\nWonogiri, 20 March 2005;\nRT 1 RW...
20    L100230096;\nSukoharjo, 16 October 2004;\nRT 3...
21    L200230034;\nKlaten, 18 November 2004;\nRT 24 ...
22    L100230180;\nLamongan, 13 May 2005;\nRT 1 RW 4...
23    L100230170;\nBoyolali, 23 February 2004;\nRT 4...
24    L100230209;\nSurakarta, 24 November 2003;\nRT ...
25    L200230036;\nSurakarta, 10 October 2005;\nRT 4...
26    L200230050;\nKlaten, 27 September 2003;\nRT 1 ...
27    L100234253;\nGrobogan, 29 June 2005;\nRT 1 RW ...
28    L100230185;\nDumai, 07 March 2005;\nRT 02 RW 0...
29    L100230239;\nSurakarta, 26 March 2004;\nRT 005...
30    L100230256;\nSragen, 20 June 2005;\nRT 07 RW 0...
31                                             04972181
32    L100230225;\nSukoharjo, 28 January 2005;\nRT 5...
33    L200230017;\nSurakarta, 06 December 2004;\nRT ...
34    L100230032;\nSurakarta, 25 February 2005;\nRT ...
35                                             06749109
36    L100230226;\nBoyolali, 22 September 2004;\nRT ...
37    L100230077;\nJayapura, 10 March 2005;\nRT 001 ...
38    L100230068;\nCilegon, 27 October 2004;\nRT 02 ...
39    L100230074;\nGrobogan, 18 February 2005;\nRT 0...
40    L100234254;\nBatang, 28 September 2005;\nRT 1 ...
41    L200230243;\nMagetan, 06 February 2005;\nRT 00...
42    L200230153;\nSragen, 04 October 2004;\nRT 08 R...
43    L100230153;\nBoyolali, 27 June 2005;\nRT 2 RW ...
44    L200234239;\nPangkalan Bun, 14 June 2004;\nRT ...
Name: CODE, dtype: object

In [ ]:
def data_cleaning(data_frame):
  cleaning_data = []

  for i in data_frame.to_list():
    element = i.split(';\n')
    if len(element) == 3:
      cleaning_data.append(element)
  return cleaning_data

In [ ]:
data_cleaned_afifah = data_cleaning(df_code_afifah)
data_cleaned_afifah_1 = data_cleaning(df_code_afifah_1)
data_cleaned_ami = data_cleaning(df_code_ami)
data_cleaned_iqbal = data_cleaning(df_code_iqbal)
data_cleaned_iqbal_1 = data_cleaning(df_code_iqbal_1)
data_cleaned_afifah

[['L100230058',
  'Karanganyar, 10 April 2001',
  'RT 02 RW 03, Kelurahan Berjo, Kecamatan Ngargoyoso,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L100230100',
  'Wonogiri, 14 September 2005',
  'RT 1 RW 3, Kelurahan Wonoboyo, Kecamatan Wonogiri,  Kabupaten Wonogiri, Jawa Tengah'],
 ['L100230095',
  'Sukoharjo, 08 February 2005',
  'RT 1 RW 5, Kelurahan Grogol, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L200234018',
  'Salatiga, 05 May 2005',
  'RT 01 RW 03, Kelurahan Kalibening, Kecamatan Tingkir,  Kota Salatiga, Jawa Tengah'],
 ['L200234096',
  'Karanganyar, 03 June 2005',
  'RT 06 RW 01, Kelurahan Gagaksipat, Kecamatan Ngemplak,  Kabupaten Boyolali, Jawa Tengah'],
 ['L100230079',
  'Grobogan, 16 April 2005',
  'RT 5 RW 19, Kelurahan Purwodadi, Kecamatan Purwodadi,  Kabupaten Grobogan, Jawa Tengah'],
 ['L200230022',
  'Sragen, 10 November 2004',
  'RT 04 RW 05, Kelurahan Cemani, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L200230026',
  'Surabaya, 03 May 2005',
  'RT 5 RW 4, Kelurahan Sumber Rejo, Kecamatan Pakal,  Kota Surabaya, Jawa Timur'],
 ['L100234250',
  'Ponorogo, 25 July 2004',
  'RT 01 RW 01, Kelurahan Patihan Kidul, Kecamatan Siman,  Kabupaten Ponorogo, Jawa Timur'],
 ['L100234263',
  'Karanganyar, 22 November 2004',
  'RT 9 RW 6, Kelurahan Ngijo, Kecamatan Tasikmadu,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L100234195',
  'Pemalang, 01 November 2004',
  'RT 3 RW 4, Kelurahan Semingkir, Kecamatan Randudongkal,  Kabupaten Pemalang, Jawa Tengah'],
 ['L100230227',
  'Karanganyar, 20 December 2004',
  'RT 009 RW 005, Kelurahan Kamalaputi, Kecamatan Kota Waingapu,  Kabupaten Sumba Timur, Nusa Tenggara Timur'],
 ['L100230144',
  'Sukoharjo, 27 February 2005',
  'RT 4 RW 1, Kelurahan Madegondo, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L100230184',
  'Ngawi, 19 October 2004',
  'RT 2 RW 1, Kelurahan Kasreman, Kecamatan Geneng,  Kabupaten Ngawi, Jawa Timur'],
 ['L100230196',
  'Klaten, 14 January 2005',
  'RT 3 RW 9, Kelurahan Sukasari, Kecamatan Serang Baru,  Kabupaten Bekasi, Jawa Barat'],
 ['L100230149',
  'Pati, 18 December 2004',
  'RT 3 RW 2, Kelurahan Mojoagung, Kecamatan Trangkil,  Kabupaten Pati, Jawa Tengah'],
 ['L200230101',
  'Karanganyar, 06 September 2004',
  'RT 4 RW 11, Kelurahan Bolon, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L200230093',
  'Gunung Makmur, 03 December 2004',
  'RT 014 RW 003, Kelurahan Gunung Makmur, Kecamatan Antang Kalang,  Kabupaten Kotawaringin Timur, Kalimantan Tengah'],
 ['L200230038',
  'Karanganyar, 26 March 2005',
  'RT 1 RW 4, Kelurahan Paulan, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L200230056',
  'Lubuk Betung, 18 March 2005',
  'RT 0 RW 0, Kelurahan Lubuk Betung, Kecamatan Merapi Selatan,  Kabupaten Lahat, Sumatera Selatan'],
 ['L200230061',
  'Klaten, 19 October 2004',
  'RT 03 RW 03, Kelurahan Kepanjen, Kecamatan Delanggu,  Kabupaten Klaten, Jawa Tengah'],
 ['L100234243',
  'Klaten, 24 February 2006',
  'RT 14 RW 07, Kelurahan Tulung, Kecamatan Tulung,  Kabupaten Klaten, Jawa Tengah'],
 ['L100230054',
  'Karanganyar, 29 September 2005',
  'RT 001 RW 007, Kelurahan Tohudan, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L200230065',
  'Sukoharjo, 01 June 2005',
  'RT 1 RW 12, Kelurahan Gayam, Kecamatan Sukoharjo,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L200230033',
  'Surakarta, 30 September 2004',
  'RT 3 RW 5, Kelurahan Bumi, Kecamatan Laweyan,  Kota Surakarta, Jawa Tengah'],
 ['L100230099',
  'Magetan, 21 March 2005',
  'RT 1 RW 4, Kelurahan Milangasri, Kecamatan Panekan,  Kabupaten Magetan, Jawa Timur'],
 ['L100230094',
  'Banten, 29 September 2005',
  'RT 09 RW 09, Kelurahan Jatireja, Kecamatan Cikarang Timur,  Kabupaten Bekasi, Jawa Barat'],
 ['L100230138',
  'Suka Cinta, 17 June 2005',
  'RT 01 RW 04, Kelurahan Atung Bungsu, Kecamatan Dempo Selatan,  Kota Pagar Alam, Sumatera Selatan'],
 ['L200230257',
  'Wonogiri, 17 May 2004',
  'RT 01 RW 02, Kelurahan Made, Kecamatan Slogohimo,  Kabupaten Wonogiri, Jawa Tengah'],
 ['L200239281',
  'Surakarta, 07 December 2005',
  'RT 02 RW 21, Kelurahan Makamhaji, Kecamatan Kartasura,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L200230245',
  'Bogor, 08 August 2005',
  'RT 001 RW 007, Kelurahan Pasirlaja, Kecamatan Sukaraja,  Kabupaten Bogor, Jawa Barat'],
 ['L100230238',
  'Nganjuk, 24 September 2004',
  'RT 1 RW 4, Kelurahan Mangun Dikaran, Kecamatan Nganjuk,  Kabupaten Nganjuk, Jawa Timur'],
 ['L100230229',
  'Sukoharjo, 16 June 2005',
  'RT 02 RW 06, Kelurahan Blulukan, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L200230259',
  'Karanganyar, 16 June 2005',
  'RT 4 RW 11, Kelurahan Jaten, Kecamatan Jaten,  Kabupaten Karanganyar, Jawa Tengah'],
 ['L200230206',
  'Surakarta, 09 April 2005',
  'RT 005 RW 006, Kelurahan Punggawan, Kecamatan Banjarsari,  Kota Surakarta, Jawa Tengah'],
 ['L100230176',
  'Sukoharjo, 13 May 2005',
  'RT 1 RW 2, Kelurahan Jati, Kecamatan Gatak,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['L100230164',
  'Boyolali, 11 April 2005',
  'RT 3 RW 2, Kelurahan Donohudan, Kecamatan Ngemplak,  Kabupaten Boyolali, Jawa Tengah'],
 ['L200230156',
  'Bangka Tengah, 21 February 2005',
  'RT 009 RW 000, Kelurahan Koba, Kecamatan Koba,  Kabupaten Bangka Tengah, Kepulauan Bangka Belitung'],
 ['L200230137',
  'Grobogan, 12 November 2005',
  'RT 03 RW 04, Kelurahan Plosoharjo, Kecamatan Toroh,  Kabupaten Grobogan, Jawa Tengah'],
 ['L200239192',
  'Sragen, 02 January 2005',
  'RT 07 RW 0, Kelurahan Donoyudan, Kecamatan Kalijambe,  Kabupaten Sragen, Jawa Tengah'],
 ['L200239282',
  'Klaten, 04 September 2004',
  'RT 7 RW 2, Kelurahan Temuwangi, Kecamatan Pedan,  Kabupaten Klaten, Jawa Tengah']]

In [ ]:
new_data_afifah = pd.DataFrame(data_cleaned_afifah, columns=("NIM", "TTL", "Alamat"))
new_data_afifah_1 = pd.DataFrame(data_cleaned_afifah_1, columns=("NIM", "TTL", "Alamat"))
new_data_ami = pd.DataFrame(data_cleaned_ami, columns=("NIM", "TTL", "Alamat"))
new_data_iqbal = pd.DataFrame(data_cleaned_iqbal, columns=("NIM", "TTL", "Alamat"))
new_data_iqbal_1 = pd.DataFrame(data_cleaned_iqbal_1, columns=("NIM", "TTL", "Alamat"))

new_data_iqbal

,NIM,TTL,Alamat
0,L200230066,"Sragen, 06 December 2004","RT 9 RW 0, Kelurahan Mojodoyong, Kecamatan Ked..."
1,D200230156,"Pati, 12 August 2004","RT 2 RW 7, Kelurahan Tunjungrejo, Kecamatan Ma..."
2,L200230015,"Kab.Semarang, 19 November 2005","RT 08 RW 01, Kelurahan Duren, Kecamatan Tengar..."
3,L100230136,"Klaten, 15 October 2005","RT 2 RW 2, Kelurahan Kingkang, Kecamatan Wonos..."
4,L200230040,"Sragen, 16 June 2005","RT 8 RW 4, Kelurahan Banaran, Kecamatan Kalija..."
...,...,...,...
74,L200234275,"Kab. Sukoharjo, 17 August 2005","RT 3 RW 6, Kelurahan Bakalan, Kecamatan Poloka..."
75,L200238290,"Surakarta, 06 September 2005","RT 06 RW 11, Kelurahan Manahan, Kecamatan Banj..."
76,L200230207,"Sukoharjo, 12 March 2005","RT 4 RW 1, Kelurahan Combongan, Kecamatan Suko..."
77,L100230001,"Surakarta, 01 May 2003","RT 06 RW 05, Kelurahan Keprabon, Kecamatan Ban..."
78,L100230065,"Surakarta, 20 November 2004","RT 2 RW 12, Kelurahan Pasar Kliwon, Kecamatan ..."

In [ ]:
filtered_df_afifah = new_data_afifah[new_data_afifah['NIM'].str.startswith('L')]
filtered_df_afifah_1 = new_data_afifah_1[new_data_afifah_1['NIM'].str.startswith('L')]
filtered_df_ami = new_data_ami[new_data_ami['NIM'].str.startswith('L')]
filtered_df_iqbal = new_data_iqbal[new_data_iqbal['NIM'].str.startswith('L')]
filtered_df_iqbal_1 = new_data_iqbal_1[new_data_iqbal_1['NIM'].str.startswith('L')]

filtered_df_afifah

,NIM,TTL,Alamat
0,L100230058,"Karanganyar, 10 April 2001","RT 02 RW 03, Kelurahan Berjo, Kecamatan Ngargo..."
1,L100230100,"Wonogiri, 14 September 2005","RT 1 RW 3, Kelurahan Wonoboyo, Kecamatan Wonog..."
2,L100230095,"Sukoharjo, 08 February 2005","RT 1 RW 5, Kelurahan Grogol, Kecamatan Grogol,..."
3,L200234018,"Salatiga, 05 May 2005","RT 01 RW 03, Kelurahan Kalibening, Kecamatan T..."
4,L200234096,"Karanganyar, 03 June 2005","RT 06 RW 01, Kelurahan Gagaksipat, Kecamatan N..."
5,L100230079,"Grobogan, 16 April 2005","RT 5 RW 19, Kelurahan Purwodadi, Kecamatan Pur..."
6,L200230022,"Sragen, 10 November 2004","RT 04 RW 05, Kelurahan Cemani, Kecamatan Grogo..."
7,L200230026,"Surabaya, 03 May 2005","RT 5 RW 4, Kelurahan Sumber Rejo, Kecamatan Pa..."
8,L100234250,"Ponorogo, 25 July 2004","RT 01 RW 01, Kelurahan Patihan Kidul, Kecamata..."
9,L100234263,"Karanganyar, 22 November 2004","RT 9 RW 6, Kelurahan Ngijo, Kecamatan Tasikmad..."
10,L100234195,"Pemalang, 01 November 2004","RT 3 RW 4, Kelurahan Semingkir, Kecamatan Rand..."
11,L100230227,"Karanganyar, 20 December 2004","RT 009 RW 005, Kelurahan Kamalaputi, Kecamatan..."
12,L100230144,"Sukoharjo, 27 February 2005","RT 4 RW 1, Kelurahan Madegondo, Kecamatan Grog..."
13,L100230184,"Ngawi, 19 October 2004","RT 2 RW 1, Kelurahan Kasreman, Kecamatan Genen..."
14,L100230196,"Klaten, 14 January 2005","RT 3 RW 9, Kelurahan Sukasari, Kecamatan Seran..."
15,L100230149,"Pati, 18 December 2004","RT 3 RW 2, Kelurahan Mojoagung, Kecamatan Tran..."
16,L200230101,"Karanganyar, 06 September 2004","RT 4 RW 11, Kelurahan Bolon, Kecamatan Colomad..."
17,L200230093,"Gunung Makmur, 03 December 2004","RT 014 RW 003, Kelurahan Gunung Makmur, Kecama..."
18,L200230038,"Karanganyar, 26 March 2005","RT 1 RW 4, Kelurahan Paulan, Kecamatan Colomad..."
19,L200230056,"Lubuk Betung, 18 March 2005","RT 0 RW 0, Kelurahan Lubuk Betung, Kecamatan M..."
20,L200230061,"Klaten, 19 October 2004","RT 03 RW 03, Kelurahan Kepanjen, Kecamatan Del..."
21,L100234243,"Klaten, 24 February 2006","RT 14 RW 07, Kelurahan Tulung, Kecamatan Tulun..."
22,L100230054,"Karanganyar, 29 September 2005","RT 001 RW 007, Kelurahan Tohudan, Kecamatan Co..."
23,L200230065,"Sukoharjo, 01 June 2005","RT 1 RW 12, Kelurahan Gayam, Kecamatan Sukohar..."
24,L200230033,"Surakarta, 30 September 2004","RT 3 RW 5, Kelurahan Bumi, Kecamatan Laweyan, ..."
25,L100230099,"Magetan, 21 March 2005","RT 1 RW 4, Kelurahan Milangasri, Kecamatan Pan..."
26,L100230094,"Banten, 29 September 2005","RT 09 RW 09, Kelurahan Jatireja, Kecamatan Cik..."
27,L100230138,"Suka Cinta, 17 June 2005","RT 01 RW 04, Kelurahan Atung Bungsu, Kecamatan..."
28,L200230257,"Wonogiri, 17 May 2004","RT 01 RW 02, Kelurahan Made, Kecamatan Slogohi..."
29,L200239281,"Surakarta, 07 December 2005","RT 02 RW 21, Kelurahan Makamhaji, Kecamatan Ka..."
30,L200230245,"Bogor, 08 August 2005","RT 001 RW 007, Kelurahan Pasirlaja, Kecamatan ..."
31,L100230238,"Nganjuk, 24 September 2004","RT 1 RW 4, Kelurahan Mangun Dikaran, Kecamatan..."
32,L100230229,"Sukoharjo, 16 June 2005","RT 02 RW 06, Kelurahan Blulukan, Kecamatan Col..."
33,L200230259,"Karanganyar, 16 June 2005","RT 4 RW 11, Kelurahan Jaten, Kecamatan Jaten, ..."
34,L200230206,"Surakarta, 09 April 2005","RT 005 RW 006, Kelurahan Punggawan, Kecamatan ..."
35,L100230176,"Sukoharjo, 13 May 2005","RT 1 RW 2, Kelurahan Jati, Kecamatan Gatak, K..."
36,L100230164,"Boyolali, 11 April 2005","RT 3 RW 2, Kelurahan Donohudan, Kecamatan Ngem..."
37,L200230156,"Bangka Tengah, 21 February 2005","RT 009 RW 000, Kelurahan Koba, Kecamatan Koba,..."
38,L200230137,"Grobogan, 12 November 2005","RT 03 RW 04, Kelurahan Plosoharjo, Kecamatan T..."
39,L200239192,"Sragen, 02 January 2005","RT 07 RW 0, Kelurahan Donoyudan, Kecamatan Kal..."
40,L200239282,"Klaten, 04 September 2004","RT 7 RW 2, Kelurahan Temuwangi, Kecamatan Peda..."

In [ ]:
combinated_data_akhwat = pd.concat([filtered_df_afifah, filtered_df_afifah_1, filtered_df_ami], ignore_index=True)
combinated_data_ikhwan = pd.concat([filtered_df_iqbal, filtered_df_iqbal_1], ignore_index=True)

final_data_akhwat = combinated_data_akhwat
duplicated_data_akhwat = combinated_data_akhwat[combinated_data_akhwat.duplicated()]
final_data_ikhwan = combinated_data_ikhwan
duplicated_data_ikhwan = combinated_data_ikhwan[combinated_data_ikhwan.duplicated()]

final_data_akhwat

,NIM,TTL,Alamat
0,L100230058,"Karanganyar, 10 April 2001","RT 02 RW 03, Kelurahan Berjo, Kecamatan Ngargo..."
1,L100230100,"Wonogiri, 14 September 2005","RT 1 RW 3, Kelurahan Wonoboyo, Kecamatan Wonog..."
2,L100230095,"Sukoharjo, 08 February 2005","RT 1 RW 5, Kelurahan Grogol, Kecamatan Grogol,..."
3,L200234018,"Salatiga, 05 May 2005","RT 01 RW 03, Kelurahan Kalibening, Kecamatan T..."
4,L200234096,"Karanganyar, 03 June 2005","RT 06 RW 01, Kelurahan Gagaksipat, Kecamatan N..."
...,...,...,...
116,L100234254,"Batang, 28 September 2005","RT 1 RW 1, Kelurahan Kalisalak, Kecamatan Bata..."
117,L200230243,"Magetan, 06 February 2005","RT 005 RW 002, Kelurahan Setren, Kecamatan Ben..."
118,L200230153,"Sragen, 04 October 2004","RT 08 RW 02, Kelurahan Plumbungan, Kecamatan K..."
119,L100230153,"Boyolali, 27 June 2005","RT 2 RW 5, Kelurahan Donohudan, Kecamatan Ngem..."
120,L200234239,"Pangkalan Bun, 14 June 2004","RT 17 RW 0, Kelurahan Pasir Panjang, Kecamatan..."

In [ ]:
duplicated_data_akhwat

,NIM,TTL,Alamat
41,L100230058,"Karanganyar, 10 April 2001","RT 02 RW 03, Kelurahan Berjo, Kecamatan Ngargo..."
42,L100230100,"Wonogiri, 14 September 2005","RT 1 RW 3, Kelurahan Wonoboyo, Kecamatan Wonog..."
43,L100230095,"Sukoharjo, 08 February 2005","RT 1 RW 5, Kelurahan Grogol, Kecamatan Grogol,..."
44,L200234018,"Salatiga, 05 May 2005","RT 01 RW 03, Kelurahan Kalibening, Kecamatan T..."
45,L200234096,"Karanganyar, 03 June 2005","RT 06 RW 01, Kelurahan Gagaksipat, Kecamatan N..."
46,L100230079,"Grobogan, 16 April 2005","RT 5 RW 19, Kelurahan Purwodadi, Kecamatan Pur..."
47,L200230022,"Sragen, 10 November 2004","RT 04 RW 05, Kelurahan Cemani, Kecamatan Grogo..."
48,L200230026,"Surabaya, 03 May 2005","RT 5 RW 4, Kelurahan Sumber Rejo, Kecamatan Pa..."
49,L100234250,"Ponorogo, 25 July 2004","RT 01 RW 01, Kelurahan Patihan Kidul, Kecamata..."
50,L100234263,"Karanganyar, 22 November 2004","RT 9 RW 6, Kelurahan Ngijo, Kecamatan Tasikmad..."
51,L100234195,"Pemalang, 01 November 2004","RT 3 RW 4, Kelurahan Semingkir, Kecamatan Rand..."
52,L100230227,"Karanganyar, 20 December 2004","RT 009 RW 005, Kelurahan Kamalaputi, Kecamatan..."
53,L100230144,"Sukoharjo, 27 February 2005","RT 4 RW 1, Kelurahan Madegondo, Kecamatan Grog..."
54,L100230184,"Ngawi, 19 October 2004","RT 2 RW 1, Kelurahan Kasreman, Kecamatan Genen..."
55,L100230196,"Klaten, 14 January 2005","RT 3 RW 9, Kelurahan Sukasari, Kecamatan Seran..."
56,L100230149,"Pati, 18 December 2004","RT 3 RW 2, Kelurahan Mojoagung, Kecamatan Tran..."
57,L200230101,"Karanganyar, 06 September 2004","RT 4 RW 11, Kelurahan Bolon, Kecamatan Colomad..."
58,L200230093,"Gunung Makmur, 03 December 2004","RT 014 RW 003, Kelurahan Gunung Makmur, Kecama..."
59,L200230038,"Karanganyar, 26 March 2005","RT 1 RW 4, Kelurahan Paulan, Kecamatan Colomad..."
60,L200230056,"Lubuk Betung, 18 March 2005","RT 0 RW 0, Kelurahan Lubuk Betung, Kecamatan M..."
61,L200230061,"Klaten, 19 October 2004","RT 03 RW 03, Kelurahan Kepanjen, Kecamatan Del..."
62,L100234243,"Klaten, 24 February 2006","RT 14 RW 07, Kelurahan Tulung, Kecamatan Tulun..."
63,L100230054,"Karanganyar, 29 September 2005","RT 001 RW 007, Kelurahan Tohudan, Kecamatan Co..."
64,L200230065,"Sukoharjo, 01 June 2005","RT 1 RW 12, Kelurahan Gayam, Kecamatan Sukohar..."
65,L200230033,"Surakarta, 30 September 2004","RT 3 RW 5, Kelurahan Bumi, Kecamatan Laweyan, ..."
66,L100230099,"Magetan, 21 March 2005","RT 1 RW 4, Kelurahan Milangasri, Kecamatan Pan..."
67,L100230094,"Banten, 29 September 2005","RT 09 RW 09, Kelurahan Jatireja, Kecamatan Cik..."
68,L100230138,"Suka Cinta, 17 June 2005","RT 01 RW 04, Kelurahan Atung Bungsu, Kecamatan..."
69,L200230257,"Wonogiri, 17 May 2004","RT 01 RW 02, Kelurahan Made, Kecamatan Slogohi..."
70,L200239281,"Surakarta, 07 December 2005","RT 02 RW 21, Kelurahan Makamhaji, Kecamatan Ka..."
71,L200230245,"Bogor, 08 August 2005","RT 001 RW 007, Kelurahan Pasirlaja, Kecamatan ..."
72,L100230238,"Nganjuk, 24 September 2004","RT 1 RW 4, Kelurahan Mangun Dikaran, Kecamatan..."
73,L100230229,"Sukoharjo, 16 June 2005","RT 02 RW 06, Kelurahan Blulukan, Kecamatan Col..."
74,L200230259,"Karanganyar, 16 June 2005","RT 4 RW 11, Kelurahan Jaten, Kecamatan Jaten, ..."
75,L200230206,"Surakarta, 09 April 2005","RT 005 RW 006, Kelurahan Punggawan, Kecamatan ..."
76,L100230176,"Sukoharjo, 13 May 2005","RT 1 RW 2, Kelurahan Jati, Kecamatan Gatak, K..."
77,L100230164,"Boyolali, 11 April 2005","RT 3 RW 2, Kelurahan Donohudan, Kecamatan Ngem..."

In [ ]:
final_data_ikhwan

,NIM,TTL,Alamat
0,L200230066,"Sragen, 06 December 2004","RT 9 RW 0, Kelurahan Mojodoyong, Kecamatan Ked..."
1,L200230015,"Kab.Semarang, 19 November 2005","RT 08 RW 01, Kelurahan Duren, Kecamatan Tengar..."
2,L100230136,"Klaten, 15 October 2005","RT 2 RW 2, Kelurahan Kingkang, Kecamatan Wonos..."
3,L200230040,"Sragen, 16 June 2005","RT 8 RW 4, Kelurahan Banaran, Kecamatan Kalija..."
4,L200230197,"Jakarta, 07 September 2004","RT 5 RW 0, Kelurahan Karangwaru, Kecamatan Plu..."
...,...,...,...
149,L200230222,"Karawang, 29 April 2005","RT 08 RW 08, Kelurahan Wadas, Kecamatan Telukj..."
150,L200238271,"Bandung, 15 October 2004","RT 003 RW 001, Kelurahan Burangrang, Kecamatan..."
151,L200234275,"Kab. Sukoharjo, 17 August 2005","RT 3 RW 6, Kelurahan Bakalan, Kecamatan Poloka..."
152,L200238290,"Surakarta, 06 September 2005","RT 06 RW 11, Kelurahan Manahan, Kecamatan Banj..."
153,L200230207,"Sukoharjo, 12 March 2005","RT 4 RW 1, Kelurahan Combongan, Kecamatan Suko..."

In [ ]:
duplicated_data_ikhwan

,NIM,TTL,Alamat
78,L200230066,"Sragen, 06 December 2004","RT 9 RW 0, Kelurahan Mojodoyong, Kecamatan Ked..."
79,L200230015,"Kab.Semarang, 19 November 2005","RT 08 RW 01, Kelurahan Duren, Kecamatan Tengar..."
80,L100230136,"Klaten, 15 October 2005","RT 2 RW 2, Kelurahan Kingkang, Kecamatan Wonos..."
81,L200230040,"Sragen, 16 June 2005","RT 8 RW 4, Kelurahan Banaran, Kecamatan Kalija..."
82,L200230197,"Jakarta, 07 September 2004","RT 5 RW 0, Kelurahan Karangwaru, Kecamatan Plu..."
...,...,...,...
149,L200230222,"Karawang, 29 April 2005","RT 08 RW 08, Kelurahan Wadas, Kecamatan Telukj..."
150,L200238271,"Bandung, 15 October 2004","RT 003 RW 001, Kelurahan Burangrang, Kecamatan..."
151,L200234275,"Kab. Sukoharjo, 17 August 2005","RT 3 RW 6, Kelurahan Bakalan, Kecamatan Poloka..."
152,L200238290,"Surakarta, 06 September 2005","RT 06 RW 11, Kelurahan Manahan, Kecamatan Banj..."
153,L200230207,"Sukoharjo, 12 March 2005","RT 4 RW 1, Kelurahan Combongan, Kecamatan Suko..."

In [ ]:
final_data_akhwat.to_excel("Cinsub_9_Des_2023_FKI_Akhwat_Final.xlsx")
final_data_ikhwan.to_excel("Cinsub_9_Des_2023_FKI_Ikhwan_Final.xlsx")