<a href="https://colab.research.google.com/github/Abstrakx/mentoring-fki/blob/main/KMP_Cinsub_Preprocessing_25_Nov_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Data Preprocessing KMP** (25-Nov-2023)

**Process :**
1. Import data using `!wget`
2. Read excel data using pandas library
3. Get the `"CODE"` coloumns for processing data
4. Using `data_cleaning` function
5. Get new data into new variable
6. Using pd.concat to get final data and split it into `final_data` and `duplicated_data`
7. If no duplicated data export data frame to excel using to_excel

Ikhwan Data usage:
* Cinsub_4_Fakultas Lain Ikhwan.xls

Akhwat Data usage:
* Cinsub_4_Fakultas Lain Akhwat.xls
* Cinsub_4_Fakultas Lain Akhwat_1.xls
* Cinsub_4_Fakultas Lain Akhwat_2.xls
* Cinsub_4_Fakultas Lain Akhwat_3.xls

In [1]:
import pandas as pd

# Read dataset
data_ikhwan_mix = pd.read_excel("Cinsub_4_Fakultas Lain Ikhwan.xls")
data_akhwat_mix = pd.read_excel("Cinsub_4_Fakultas Lain Akhwat.xls")
data_akhwat_mix_1 = pd.read_excel("Cinsub_4_Fakultas Lain Akhwat_1.xls")
data_akhwat_mix_2 = pd.read_excel("Cinsub_4_Fakultas Lain Akhwat_2.xls")
data_akhwat_mix_3 = pd.read_excel("Cinsub_4_Fakultas Lain Akhwat_3.xls")


df_ikhwan = pd.DataFrame(data_ikhwan_mix)
df_akhwat = pd.DataFrame(data_akhwat_mix)
df_akhwat_1 = pd.DataFrame(data_akhwat_mix_1)
df_akhwat_2 = pd.DataFrame(data_akhwat_mix_2)
df_akhwat_3 = pd.DataFrame(data_akhwat_mix_3)


df_ikhwan

                   TIME                                               CODE
0   2023-11-25 04:56:58  D200230048;\nWonogiri, 12 June 2001;\nRT 01 RW...
1   2023-11-25 04:57:03  D200230039;\nKlaten, 05 October 2005;\nRT 1 RW...
2   2023-11-25 04:57:13                                         D600210234
3   2023-11-25 04:57:16  L200230039;\nPati, 11 October 2004;\nRT 5 RW 1...
4   2023-11-25 04:57:22  C100230331;\nKabupaten Wonogiri, 08 February 2...
..                  ...                                                ...
78  2023-11-25 05:04:35  D300230141;\nPati, 29 April 2006;\nRT 04 RW 01...
79  2023-11-25 05:04:54                                         B200230279
80  2023-11-25 05:05:04  G000230077;\nBoyolali, 23 November 2004;\nRT 1...
81  2023-11-25 05:06:26                                         D400230069
82  2023-11-25 05:07:40                                         B200230458

[83 rows x 2 columns]

In [2]:
df_code_ikhwan = df_ikhwan[0:]["CODE"]
df_code_akhwat = df_akhwat[0:]["CODE"]
df_code_akhwat_1 = df_akhwat_1[0:]["CODE"]
df_code_akhwat_2 = df_akhwat_2[0:]["CODE"]
df_code_akhwat_3 = df_akhwat_3[0:]["CODE"]

df_code_ikhwan

0     D200230048;\nWonogiri, 12 June 2001;\nRT 01 RW...
1     D200230039;\nKlaten, 05 October 2005;\nRT 1 RW...
2                                            D600210234
3     L200230039;\nPati, 11 October 2004;\nRT 5 RW 1...
4     C100230331;\nKabupaten Wonogiri, 08 February 2...
                            ...
78    D300230141;\nPati, 29 April 2006;\nRT 04 RW 01...
79                                           B200230279
80    G000230077;\nBoyolali, 23 November 2004;\nRT 1...
81                                           D400230069
82                                           B200230458
Name: CODE, Length: 83, dtype: object

In [3]:
def data_cleaning(data_frame):
  cleaning_data = []
  cleaning_data_min_3 = []
  cleaning_data_1 = []

  for i in data_frame.to_list():
    element = i.split(';\n')
    if len(element) == 3:
      cleaning_data.append(element)
    elif len(element) < 3:
      cleaning_data_min_3.append(element)
    else:
      cleaning_data_1.append([i])

  return cleaning_data, cleaning_data_min_3, cleaning_data_1

In [4]:
data_cleaned_ikhwan = data_cleaning(df_code_ikhwan)
data_cleaned_akhwat = data_cleaning(df_code_akhwat)
data_cleaned_akhwat_1 = data_cleaning(df_code_akhwat_1)
data_cleaned_akhwat_2 = data_cleaning(df_code_akhwat_2)
data_cleaned_akhwat_3 = data_cleaning(df_code_akhwat_3)

data_cleaned_ikhwan

([['D200230048',
   'Wonogiri, 12 June 2001',
   'RT 01 RW 04, Kelurahan Gumiwanglor, Kecamatan Wuryantoro,  Kabupaten Wonogiri, Jawa Tengah'],
  ['D200230039',
   'Klaten, 05 October 2005',
   'RT 1 RW 2, Kelurahan Sidoharjo, Kecamatan Polanharjo,  Kabupaten Klaten, Jawa Tengah'],
  ['L200230039',
   'Pati, 11 October 2004',
   'RT 5 RW 1, Kelurahan Dadirejo, Kecamatan Margorejo,  Kabupaten Pati, Jawa Tengah'],
  ['C100230331',
   'Kabupaten Wonogiri, 08 February 2005',
   'RT 2 RW 4, Kelurahan Bulusulur, Kecamatan Wonogiri,  Kabupaten Wonogiri, Jawa Tengah'],
  ['D100230277',
   'Boyolali, 07 September 2005',
   'RT 3 RW 5, Kelurahan Canden, Kecamatan Sambi,  Kabupaten Boyolali, Jawa Tengah'],
  ['L200230077',
   'Pati, 12 November 2004',
   'RT 3 RW 2, Kelurahan Bumiharjo, Kecamatan Winong,  Kabupaten Pati, Jawa Tengah'],
  ['B200230299',
   'Boyolali, 13 October 2006',
   'RT 7 RW 2, Kelurahan Denggungan, Kecamatan Banyudono,  Kabupaten Boyolali, Jawa Tengah'],
  ['D200230156',
   'Pati, 12 August 2004',
   'RT 2 RW 7, Kelurahan Tunjungrejo, Kecamatan Margoyoso,  Kabupaten Pati, Jawa Tengah'],
  ['C100230068',
   'Jakarta, 01 March 2005',
   'RT 31 RW 08, Kelurahan Plumbungan, Kecamatan Karangmalang,  Kabupaten Sragen, Jawa Tengah'],
  ['D200230087',
   'Klaten, 01 January 2005',
   'RT 04 RW 20, Kelurahan Jebres, Kecamatan Jebres,  Kota Surakarta, Jawa Tengah'],
  ['C100230001',
   'Sragen, 20 July 2004',
   'RT 10 RW 01, Kelurahan Genengduwur, Kecamatan Gemolong,  Kabupaten Sragen, Jawa Tengah'],
  ['D300230019',
   'Temanggung, 27 June 2005',
   'RT 1 RW 6, Kelurahan Walitelon Selatan, Kecamatan Temanggung,  Kabupaten Temanggung, Jawa Tengah'],
  ['B200230396',
   'Karanganyar, 02 May 2005',
   'RT 1 RW 12, Kelurahan Wonorejo, Kecamatan Gondangrejo,  Kabupaten Karanganyar, Jawa Tengah'],
  ['D200230082',
   'Boyolali, 03 May 2004',
   'RT 1 RW 3, Kelurahan Karangjati, Kecamatan Wonosegoro,  Kabupaten Boyolali, Jawa Tengah'],
  ['D200230199',
   'Sukoharjo, 21 August 2005',
   'RT 3 RW 5, Kelurahan Madegondo, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['B100230075',
   'Sukoharjo, 10 November 2003',
   'RT 4 RW 1, Kelurahan Gumpang, Kecamatan Kartasura,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['D200230198',
   'Grobogan, 29 October 2004',
   'RT 04 RW 03, Kelurahan Ngembak, Kecamatan Purwodadi,  Kabupaten Grobogan, Jawa Tengah'],
  ['D200230079',
   'Sragen, 29 April 2005',
   'RT 6 RW 1, Kelurahan Ngepringan, Kecamatan Jenar,  Kabupaten Sragen, Jawa Tengah'],
  ['D200230013',
   'Sragen, 17 August 2004',
   'RT 008 RW 004, Kelurahan Banaran, Kecamatan Kalijambe,  Kabupaten Sragen, Jawa Tengah'],
  ['D200230046',
   'Surakarta, 08 July 2004',
   'RT 01 RW 05, Kelurahan Pabelan, Kecamatan Kartasura,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['D100230270',
   'Sukoharjo, 15 July 2005',
   'RT 2 RW 2, Kelurahan Ngadirejo, Kecamatan Kartasura,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['I000230051',
   'Wonogiri, 11 August 2005',
   'RT 3 RW 1, Kelurahan Ngelo, Kecamatan Jatiroto,  Kabupaten Wonogiri, Jawa Tengah'],
  ['B100230295',
   'Klaten, 21 December 2004',
   'RT 1 RW 3, Kelurahan Bero, Kecamatan Trucuk,  Kabupaten Klaten, Jawa Tengah'],
  ['D300230115',
   'Jepara, 17 January 2005',
   'RT 05 RW 02, Kelurahan Panggung, Kecamatan Kedung,  Kabupaten Jepara, Jawa Tengah'],
  ['B200230423',
   'Klaten, 09 December 2004',
   'RT 03 RW 05, Kelurahan Sawahan, Kecamatan Juwiring,  Kabupaten Klaten, Jawa Tengah'],
  ['I000230077',
   'Wonogiri, 06 May 2004',
   'RT 1 RW 1, Kelurahan Lemahbang, Kecamatan Kismantoro,  Kabupaten Wonogiri, Jawa Tengah'],
  ['D200230274',
   'Madiun, 29 June 2004',
   'RT 69 RW 16, Kelurahan Nambangan Lor, Kecamatan Mangu Harjo,  Kota Madiun, Jawa Timur'],
  ['D200230058',
   'Batang, 13 November 2004',
   'RT 3 RW 4, Kelurahan Pasekaran, Kecamatan Batang,  Kabupaten Batang, Jawa Tengah'],
  ['L200230002',
   'Sukoharjo, 06 August 2004',
   'RT 2 RW 16, Kelurahan Makamhaji, Kecamatan Kartasura,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['D200230038',
   'Sukoharjo, 11 March 2005',
   'RT 02 RW 07, Kelurahan Kwarasan, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['D200230069',
   'Grobogan, 25 May 2005',
   'RT 5 RW 2, Kelurahan Putat, Kecamatan Purwodadi,  Kabupaten Grobogan, Jawa Tengah'],
  ['D400230046',
   'Karanganyar, 27 May 2005',
   'RT 02 RW 06, Kelurahan Gawanan, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
  ['B100230559',
   'Karanganyar, 26 June 2005',
   'RT 03 RW 01, Kelurahan Tohudan, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
  ['D200230073',
   'Grobogan, 12 September 2003',
   'RT 1 RW 5, Kelurahan Tambirejo, Kecamatan Toroh,  Kabupaten Grobogan, Jawa Tengah'],
  ['D600230088',
   'Jepara, 11 February 2005',
   'RT 25 RW 5, Kelurahan Jambu Timur, Kecamatan Mlonggo,  Kabupaten Jepara, Jawa Tengah'],
  ['D200230169',
   'Karawang, 16 August 2005',
   'RT 34 RW 11, Kelurahan Telukjambe, Kecamatan Telukjambe Timur,  Kabupaten Karawang, Jawa Barat'],
  ['J500230122',
   'Surakarta, 23 July 2003',
   'RT 5 RW 18, Kelurahan Mojosongo, Kecamatan Jebres,  Kota Surakarta, Jawa Tengah'],
  ['D200230114',
   'Sragen, 10 September 2005',
   'RT 14 RW 0, Kelurahan Sidokerto, Kecamatan Plupuh,  Kabupaten Sragen, Jawa Tengah'],
  ['D600230120',
   'Sukoharjo, 28 November 2003',
   'RT 3 RW 6, Kelurahan Gentan, Kecamatan Bendosari,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['L200230175',
   'Sragen, 14 August 2005',
   'RT 5 RW 0, Kelurahan Jetis Karangpung, Kecamatan Kalijambe,  Kabupaten Sragen, Jawa Tengah'],
  ['L200230003',
   'Surakarta, 05 July 2004',
   'RT 3 RW 10, Kelurahan Gedongan, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
  ['D200230107',
   'Sukoharjo, 01 November 2003',
   'RT 4 RW 9, Kelurahan Sukoharjo, Kecamatan Sukoharjo,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['D200230262',
   'Klaten, 30 June 2005',
   'RT 02 RW 09, Kelurahan Jetis, Kecamatan Klaten Selatan,  Kabupaten Klaten, Jawa Tengah'],
  ['L200230068',
   'Wonogiri, 14 May 2005',
   'RT 01 RW 12, Kelurahan Pondok, Kecamatan Ngadirojo,  Kabupaten Wonogiri, Jawa Tengah'],
  ['D200230277',
   'Jambi, 18 December 2004',
   'RT 03 RW 01, Kelurahan Murni, Kecamatan Danau Sipin,  Kota Jambi, Jambi'],
  ['B300230116',
   'Surakarta, 14 July 2005',
   'RT 3 RW 4, Kelurahan Pajang, Kecamatan Laweyan,  Kota Surakarta, Jawa Tengah'],
  ['D200230222',
   'Sukoharjo, 20 July 2003',
   'RT 003 RW 004, Kelurahan Banaran, Kecamatan Grogol,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['L200230180',
   'Boyolali, 15 August 2005',
   'RT 2 RW 7, Kelurahan Samiran, Kecamatan Selo,  Kabupaten Boyolali, Jawa Tengah'],
  ['B300230142',
   'Surakarta, 22 March 2005',
   'RT 6 RW 7, Kelurahan Sumber, Kecamatan Banjarsari,  Kota Surakarta, Jawa Tengah'],
  ['L200230159',
   'Sukoharjo, 20 June 2005',
   'RT 1 RW 4, Kelurahan Sidorejo, Kecamatan Bendosari,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['D200230204',
   'Surakarta, 05 November 2004',
   'RT 07 RW 01, Kelurahan Joyosuran, Kecamatan Pasar Kliwon,  Kota Surakarta, Jawa Tengah'],
  ['D200230118',
   'Klaten, 26 February 2005',
   'RT 8 RW 4, Kelurahan Jatinom, Kecamatan Jatinom,  Kabupaten Klaten, Jawa Tengah'],
  ['B300230115',
   'Salatiga, 19 January 2005',
   'RT 5 RW 1, Kelurahan Pulutan, Kecamatan Sidorejo,  Kota Salatiga, Jawa Tengah'],
  ['D300230170',
   'Sragen, 24 August 2005',
   'RT 24 RW 23, Kelurahan Kadipiro, Kecamatan Sambirejo,  Kabupaten Sragen, Jawa Tengah'],
  ['D200230028',
   'Sragen, 13 August 2004',
   'RT 25 RW 7, Kelurahan Jurangjero, Kecamatan Karangmalang,  Kabupaten Sragen, Jawa Tengah'],
  ['J500230137',
   'Surakarta, 29 December 2004',
   'RT 01 RW 01, Kelurahan Gajahan, Kecamatan Colomadu,  Kabupaten Karanganyar, Jawa Tengah'],
  ['L200230141',
   'Klaten, 26 March 2005',
   'RT 5 RW 7, Kelurahan Tumpang Krasak, Kecamatan Jati,  Kabupaten Kudus, Jawa Tengah'],
  ['L200230105',
   'Sleman, 10 November 2003',
   'RT 1 RW 9, Kelurahan Matesih, Kecamatan Matesih,  Kabupaten Karanganyar, Jawa Tengah'],
  ['D200230185',
   'Klaten, 10 June 2004',
   'RT 3 RW 2, Kelurahan Pakisan, Kecamatan Cawas,  Kabupaten Klaten, Jawa Tengah'],
  ['D200230253',
   'Bekasi, 16 May 2005',
   'RT 1 RW 12, Kelurahan Satriajaya, Kecamatan Tambun Utara,  Kabupaten Bekasi, Jawa Barat'],
  ['L200230094',
   'Boyolali 04 April 2005, 04 April 2005',
   'RT 10 RW 2, Kelurahan Bendosari, Kecamatan Sawit,  Kabupaten Boyolali, Jawa Tengah'],
  ['L200230107',
   'Pacitan, 06 June 2005',
   'RT 3 RW 7, Kelurahan Sidoharjo, Kecamatan Pacitan,  Kabupaten Pacitan, Jawa Timur'],
  ['D200230177',
   'Sragen, 11 March 2005',
   'RT 2 RW 17, Kelurahan Sragen Kulon, Kecamatan Sragen,  Kabupaten Sragen, Jawa Tengah'],
  ['L200230130',
   'Sragen, 22 September 2004',
   'RT 3 RW 0, Kelurahan Pilangsari, Kecamatan Ngrampal,  Kabupaten Sragen, Jawa Tengah'],
  ['D200230188',
   'Rembang, 04 August 2004',
   'RT 1 RW 1, Kelurahan Kumendung, Kecamatan Rembang,  Kabupaten Rembang, Jawa Tengah'],
  ['G000230105',
   'Jakarta, 18 September 2004',
   'RT 1 RW 2, Kelurahan Guwotirto, Kecamatan Giriwoyo,  Kabupaten Wonogiri, Jawa Tengah'],
  ['D100230258',
   'Karanganyar, 07 July 2003',
   'RT 2 RW 5, Kelurahan Tuban, Kecamatan Gondangrejo,  Kabupaten Karanganyar, Jawa Tengah'],
  ['C100230003',
   'Surakarta, 17 June 2002',
   'RT 3 RW 26, Kelurahan Ngringo, Kecamatan Jaten,  Kabupaten Karanganyar, Jawa Tengah'],
  ['D100230269',
   'Medasari, 14 February 2006',
   'RT 2 RW 6, Kelurahan Medasari, Kecamatan Rawajitu Selatan,  Kabupaten Tulangbawang, Lampung'],
  ['L200230250',
   'Kota Madiun, 11 April 2004',
   'RT 07 RW 02, Kelurahan Bogem, Kecamatan Kawedanan,  Kabupaten Magetan, Jawa Timur'],
  ['L200230246',
   'Boyolali, 20 September 2003',
   'RT 22 RW 03, Kelurahan Kadireso, Kecamatan Teras,  Kabupaten Boyolali, Jawa Tengah'],
  ['L200230270',
   'Boyolali, 27 November 2004',
   'RT 01 RW 02, Kelurahan Sukorejo, Kecamatan Musuk,  Kabupaten Boyolali, Jawa Tengah'],
  ['L200230267',
   'Salatiga, 26 July 2004',
   'RT 2 RW 8, Kelurahan Urutsewu, Kecamatan Ampel,  Kabupaten Boyolali, Jawa Tengah'],
  ['D300230141',
   'Pati, 29 April 2006',
   'RT 04 RW 01, Kelurahan Ronggo, Kecamatan Jaken,  Kabupaten Pati, Jawa Tengah'],
  ['G000230077',
   'Boyolali, 23 November 2004',
   'RT 1 RW 5, Kelurahan Manggung, Kecamatan Ngemplak,  Kabupaten Boyolali, Jawa Tengah']],
 [['D600210234'],
  ['D100220205'],
  ['D100220190'],
  ['TTL: Sukoharjo, 01 May 2003\nAlamat: RT 02 RW 04, Kelurahan Wironanggan, Kecamatan Gatak,  Kabupaten Sukoharjo, Jawa Tengah'],
  ['D400220099'],
  ['B200230279'],
  ['D400230069'],
  ['B200230458']],
 [])

In [5]:
# Ikhwan
clean_data_ikhwan = data_cleaned_ikhwan[0]
clean_data_ikhwan_min_3 = data_cleaned_ikhwan[2]
clean_data_ikhwan_1 = data_cleaned_ikhwan[1]

# Akhwat
clean_data_akhwat = data_cleaned_akhwat[0]
clean_data_akhwat_min_3 = data_cleaned_akhwat[2]
clean_data_akhwat_1 = data_cleaned_akhwat[1]

# Akhwat_1
clean_data_akhwat_1 = data_cleaned_akhwat_1[0]
clean_data_akhwat_min_3_1 = data_cleaned_akhwat_1[2]
clean_data_akhwat_1_1 = data_cleaned_akhwat_1[1]

# Akhwat_2
clean_data_akhwat_2 = data_cleaned_akhwat_2[0]
clean_data_akhwat_min_3_2 = data_cleaned_akhwat_2[2]
clean_data_akhwat_1_2 = data_cleaned_akhwat_2[2]

# Akhwat_3
clean_data_akhwat_3 = data_cleaned_akhwat_3[0]
clean_data_akhwat_min_3_3 = data_cleaned_akhwat_3[2]
clean_data_akhwat_1_3 = data_cleaned_akhwat_3[2]


clean_data_ikhwan_1

[['D600210234'],
 ['D100220205'],
 ['D100220190'],
 ['TTL: Sukoharjo, 01 May 2003\nAlamat: RT 02 RW 04, Kelurahan Wironanggan, Kecamatan Gatak,  Kabupaten Sukoharjo, Jawa Tengah'],
 ['D400220099'],
 ['B200230279'],
 ['D400230069'],
 ['B200230458']]

In [6]:
# Looping to clean single data
def cleaning_data_single(data):
  clean_ide = []
  clean_detail = []
  for i in data:
    for x in i:
      if len(x) <= 10:
        clean_detail.append(x)
      else:
        clean_ide.append(x)
  return clean_detail

single_data_ikhwan = cleaning_data_single(clean_data_ikhwan_1)
single_data_akhwat = cleaning_data_single(clean_data_akhwat_1)
single_data_akhwat_1 = cleaning_data_single(clean_data_akhwat_1_1)
single_data_akhwat_2 = cleaning_data_single(clean_data_akhwat_1_2)
single_data_akhwat_3 = cleaning_data_single(clean_data_akhwat_1_3)

single_data_ikhwan

['D600210234',
 'D100220205',
 'D100220190',
 'D400220099',
 'B200230279',
 'D400230069',
 'B200230458']

In [18]:
new_data_ikhwan = pd.DataFrame(clean_data_ikhwan, columns=("NIM", "TTL", "Alamat"))
new_data_akhwat = pd.DataFrame(clean_data_akhwat, columns=("NIM", "TTL", "Alamat"))
new_data_akhwat_1 = pd.DataFrame(clean_data_akhwat_1, columns=("NIM", "TTL", "Alamat"))
new_data_akhwat_2 = pd.DataFrame(clean_data_akhwat_2, columns=("NIM", "TTL", "Alamat"))
new_data_akhwat_3 = pd.DataFrame(clean_data_akhwat_3, columns=("NIM", "TTL", "Alamat"))

new_single_data_ikhwan_1 = pd.DataFrame(single_data_ikhwan, columns=["NIM"])
new_single_data_akhwat_1 = pd.DataFrame(single_data_akhwat, columns=["NIM"])
new_single_data_akhwat_1_1 = pd.DataFrame(single_data_akhwat_1, columns=["NIM"])
new_single_data_akhwat_1_2 = pd.DataFrame(single_data_akhwat_2, columns=["NIM"])
new_single_data_akhwat_1_3 = pd.DataFrame(single_data_akhwat_3, columns=["NIM"])

new_single_data_akhwat_1

           NIM
0   J500230032
1   L200234018
2   L100230115
3   L100230080
4   L100230091
5   L100230097
6   L100230054
7   B100230048
8   C100230049
9   I000230014
10  C100230296

In [22]:
combinated_data_akhwat_clean = pd.concat([new_data_akhwat, new_data_akhwat_1, new_data_akhwat_2, new_data_akhwat_3], ignore_index=True)
combinated_data_akhwat_dirty = pd.concat([new_single_data_akhwat_1, new_single_data_akhwat_1_1, new_single_data_akhwat_1_2, new_single_data_akhwat_1_3], ignore_index=True)

combinated_data_ikhwan_clean = new_data_ikhwan
combinated_data_ikhwan_dirty = new_single_data_ikhwan_1

combinated_data_ikhwan_dirty

          NIM
0  D600210234
1  D100220205
2  D100220190
3  D400220099
4  B200230279
5  D400230069
6  B200230458

In [33]:
# Filtering data based on NIM Alphabet
sorted_df_ikhwan_clean = combinated_data_ikhwan_clean.sort_values(by="NIM").drop_duplicates().reset_index(drop=True)
sorted_df_ikhwan_dirty = combinated_data_ikhwan_dirty.sort_values(by="NIM").drop_duplicates().reset_index(drop=True)
sorted_df_akhwat_clean = combinated_data_akhwat_clean.sort_values(by="NIM").drop_duplicates().reset_index(drop=True)
sorted_df_akhwat_dirty = combinated_data_akhwat_dirty.sort_values(by="NIM").drop_duplicates().reset_index(drop=True)

sorted_df_ikhwan_clean

,NIM,TTL,Alamat
0,B100230075,"Sukoharjo, 10 November 2003","RT 4 RW 1, Kelurahan Gumpang, Kecamatan Kartas..."
1,B100230295,"Klaten, 21 December 2004","RT 1 RW 3, Kelurahan Bero, Kecamatan Trucuk, ..."
2,B100230559,"Karanganyar, 26 June 2005","RT 03 RW 01, Kelurahan Tohudan, Kecamatan Colo..."
3,B200230299,"Boyolali, 13 October 2006","RT 7 RW 2, Kelurahan Denggungan, Kecamatan Ban..."
4,B200230396,"Karanganyar, 02 May 2005","RT 1 RW 12, Kelurahan Wonorejo, Kecamatan Gond..."
...,...,...,...
70,L200230180,"Boyolali, 15 August 2005","RT 2 RW 7, Kelurahan Samiran, Kecamatan Selo, ..."
71,L200230246,"Boyolali, 20 September 2003","RT 22 RW 03, Kelurahan Kadireso, Kecamatan Ter..."
72,L200230250,"Kota Madiun, 11 April 2004","RT 07 RW 02, Kelurahan Bogem, Kecamatan Kaweda..."
73,L200230267,"Salatiga, 26 July 2004","RT 2 RW 8, Kelurahan Urutsewu, Kecamatan Ampel..."
74,L200230270,"Boyolali, 27 November 2004","RT 01 RW 02, Kelurahan Sukorejo, Kecamatan Mus..."

In [35]:
# Filtering data based FKI Members
filtered_df_ikhwan_fki_clean = sorted_df_ikhwan_clean[sorted_df_ikhwan_clean['NIM'].str.startswith('L')].drop_duplicates().reset_index(drop=True)
filtered_df_ikhwan_fki_dirty = sorted_df_ikhwan_dirty[sorted_df_ikhwan_dirty['NIM'].str.startswith('L')].drop_duplicates().reset_index(drop=True)
filtered_df_akhwat_fki_clean = sorted_df_akhwat_clean[sorted_df_akhwat_clean['NIM'].str.startswith('L')].drop_duplicates().reset_index(drop=True)
filtered_df_akhwat_fki_dirty = sorted_df_akhwat_dirty[sorted_df_akhwat_dirty['NIM'].str.startswith('L')].drop_duplicates().reset_index(drop=True)


filtered_df_ikhwan_fki_clean

,NIM,TTL,Alamat
0,L200230002,"Sukoharjo, 06 August 2004","RT 2 RW 16, Kelurahan Makamhaji, Kecamatan Kar..."
1,L200230003,"Surakarta, 05 July 2004","RT 3 RW 10, Kelurahan Gedongan, Kecamatan Colo..."
2,L200230039,"Pati, 11 October 2004","RT 5 RW 1, Kelurahan Dadirejo, Kecamatan Margo..."
3,L200230068,"Wonogiri, 14 May 2005","RT 01 RW 12, Kelurahan Pondok, Kecamatan Ngadi..."
4,L200230077,"Pati, 12 November 2004","RT 3 RW 2, Kelurahan Bumiharjo, Kecamatan Wino..."
5,L200230094,"Boyolali 04 April 2005, 04 April 2005","RT 10 RW 2, Kelurahan Bendosari, Kecamatan Saw..."
6,L200230105,"Sleman, 10 November 2003","RT 1 RW 9, Kelurahan Matesih, Kecamatan Matesi..."
7,L200230107,"Pacitan, 06 June 2005","RT 3 RW 7, Kelurahan Sidoharjo, Kecamatan Paci..."
8,L200230130,"Sragen, 22 September 2004","RT 3 RW 0, Kelurahan Pilangsari, Kecamatan Ngr..."
9,L200230141,"Klaten, 26 March 2005","RT 5 RW 7, Kelurahan Tumpang Krasak, Kecamatan..."
10,L200230159,"Sukoharjo, 20 June 2005","RT 1 RW 4, Kelurahan Sidorejo, Kecamatan Bendo..."
11,L200230175,"Sragen, 14 August 2005","RT 5 RW 0, Kelurahan Jetis Karangpung, Kecamat..."
12,L200230180,"Boyolali, 15 August 2005","RT 2 RW 7, Kelurahan Samiran, Kecamatan Selo, ..."
13,L200230246,"Boyolali, 20 September 2003","RT 22 RW 03, Kelurahan Kadireso, Kecamatan Ter..."
14,L200230250,"Kota Madiun, 11 April 2004","RT 07 RW 02, Kelurahan Bogem, Kecamatan Kaweda..."
15,L200230267,"Salatiga, 26 July 2004","RT 2 RW 8, Kelurahan Urutsewu, Kecamatan Ampel..."
16,L200230270,"Boyolali, 27 November 2004","RT 01 RW 02, Kelurahan Sukorejo, Kecamatan Mus..."

In [36]:
# Save Data to Local
sorted_df_ikhwan_clean.to_excel("Cinsub_4_(25-Nov-2023)_Fakultas Lain Ikhwan_Data-Bersih.xlsx")
sorted_df_ikhwan_dirty.to_excel("Cinsub_4_(25-Nov-2023)_Fakultas Lain Ikhwan_Data-Kotor.xlsx")
sorted_df_akhwat_clean.to_excel("Cinsub_4_(25-Nov-2023)_Fakultas Lain Akhwat_Data-Bersih.xlsx")
sorted_df_akhwat_dirty.to_excel("Cinsub_4_(25-Nov-2023)_Fakultas Lain Akhwat_Data-Kotor.xlsx")

,NIM,TTL,Alamat
0,L100230226,"Boyolali, 22 September 2004","RT 4 RW 4, Kelurahan Mojosongo, Kecamatan Mojo..."
1,L100230085,"Brebes, 17 September 2003","RT 02 RW 06, Kelurahan Pasar Batang, Kecamatan..."
2,L200230248,"Surakarta, 03 February 2005","RT 5 RW 28, Kelurahan Mojosongo, Kecamatan Jeb..."
3,L100234263,"Karanganyar, 22 November 2004","RT 9 RW 6, Kelurahan Ngijo, Kecamatan Tasikmad..."
4,L100234250,"Ponorogo, 25 July 2004","RT 01 RW 01, Kelurahan Patihan Kidul, Kecamata..."
...,...,...,...
111,L200230182,"Sragen, 08 May 2005","RT 27 RW 12, Kelurahan Ngarum, Kecamatan Ngram..."
112,L100230160,"Karanganyar, 01 July 2005","RT 01 RW 06, Kelurahan Bakalan, Kecamatan Juma..."
113,L100230008,"Wonosobo, 16 November 2003","RT 03 RW 06, Kelurahan Bumireso, Kecamatan Won..."
114,L200239192,"Sragen, 02 January 2005","RT 07 RW 0, Kelurahan Donoyudan, Kecamatan Kal..."
115,L100230199,"Sragen, 30 December 2004","RT 1 RW 1, Kelurahan Jati, Kecamatan Masaran, ..."

In [37]:
# Save Data to Local
filtered_df_ikhwan_fki_clean.to_excel("Cinsub_4_(25-Nov-2023)_FKI-Ikhwan_Data-Bersih.xlsx")
filtered_df_ikhwan_fki_dirty.to_excel("Cinsub_4_(25-Nov-2023)_FKI-Ikhwan_Data-Kotor.xlsx")
filtered_df_akhwat_fki_clean.to_excel("Cinsub_4_(25-Nov-2023)_FKI-Akhwat_Data-Bersih.xlsx")
filtered_df_akhwat_fki_dirty.to_excel("Cinsub_4_(25-Nov-2023)_FKI-Akhwat_Data-Kotor.xlsx")